name: Manual Release

on:
  workflow_dispatch:
    inputs:
      release_name:
        description: 'Name of release'
        required: true
        type: string
      release_body:
        description: 'Description of release'
        required: true
        type: string

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current branch
      uses: actions/checkout@v3

    - name: Set up variables
      id: vars
      run: |
        BRANCH_NAME="${GITHUB_REF##*/}"
        VERSION="${BRANCH_NAME//\//-}-$(date +%Y%m%d%H%M%S)"
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Prepare release directory
      run: |
        mkdir -p release/extensions
        mv README.md LICENSE release/extensions/

        rsync -av --exclude='.git' --exclude='release' ./ release/

        tar -czf panel.tar.gz -C release $(ls release)

    - name: Create GitHub release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.vars.outputs.version }}
        name: ${{ github.event.inputs.release_name }}
        body: ${{ github.event.inputs.release_body }}
        files: panel.tar.gz
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
